name: 🎮 Godot — Engine Support
description: Report a bug, request a feature, or contribute to Godot integration
title: "[Godot]: "
labels: ["engine: godot"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for anything related to **Godot Engine** support in SOG.
        > ⚠️ Godot support is currently **planned/in development**. Contributions are very welcome!
        > Check [CONTRIBUTING.md](https://github.com/RagsProjects/Sew-Own-Game/blob/main/CONTRIBUTING.md) if you'd like to help add Godot support.

  - type: dropdown
    id: type
    attributes:
      label: 📌 Issue Type
      options:
        - Bug — Something isn't working correctly
        - Feature Request — Add or improve a Godot-specific feature
        - Contribution — I want to help implement Godot support
        - Improvement — Enhance existing Godot support
        - Question — I need help with Godot integration
    validations:
      required: true

  - type: dropdown
    id: godot_version
    attributes:
      label: 🔢 Godot Version
      options:
        - Godot 4.x (GDScript)
        - Godot 4.x (C#/.NET)
        - Godot 3.x (GDScript)
        - Godot 3.x (C#/.NET)
        - Godot 3.x (GDNative)
        - Other
    validations:
      required: true

  - type: input
    id: godot_version_exact
    attributes:
      label: Exact Godot Version
      placeholder: "e.g. 4.2.1, 3.5.3"
    validations:
      required: true

  - type: dropdown
    id: scripting_language
    attributes:
      label: 📝 Primary Scripting Language
      options:
        - GDScript
        - C# (.NET)
        - C++ (GDExtension)
        - Visual Script (deprecated)
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 🖥️ Operating System
      options:
        - Windows 11
        - Windows 10
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📋 Description
      description: Describe the bug, feature, or your contribution plan.
      placeholder: |
        **If bug:** SOG fails to detect Godot projects because it doesn't recognize project.godot files...
        **If feature:** SOG should parse project.godot to extract the project name and renderer...
        **If contribution:** I'd like to implement Godot support by scanning for project.godot files...
    validations:
      required: true

  - type: textarea
    id: project_godot_notes
    attributes:
      label: 📄 project.godot Notes (optional)
      description: Any relevant details about the project's `project.godot` or `.godot/` folder structure.
      placeholder: "The project uses the Forward+ renderer and has addons enabled..."

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Steps to Reproduce (for bugs)
      placeholder: |
        1. Open SOG
        2. ...

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior (for bugs)

  - type: textarea
    id: logs
    attributes:
      label: 📄 Logs / Error Output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context

  - type: checkboxes
    id: checklist
    attributes:
      label: ✔️ Checklist
      options:
        - label: I searched for existing Godot-related issues before submitting
          required: true
        - label: I am aware that Godot support is still being developed
          required: true
